### Espaçamento da Janela (Padding)
window_padding_width 6

### Fontes
font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.5

### Tema: Whale (Cores Principais)
background #1a1e2a
foreground #ffffff

### Cores Normais (0-7)
color0  #1d2430
color1  #fa5ead
color2  #00fbad
color3  #ffdf5f
color4  #5eadfc
color5  #fa5ead
color6  #27dcff
color7  #ffffff

### Cores Brilhantes (8-15)
color8  #1d2430
color9  #fa5ead
color10 #00fbad
color11 #ffdf5f
color12 #5eadfc
color13 #fa5ead
color14 #6a6f87
color15 #eff1f5
